server:
  port: ${port:8080}
spring:
  application:
    name: service-user
  cloud:
    kubernetes:
      discovery:
        enabled: true
        serviceLabels: #只访问以下带有标签的服务
          app: nginx
management:
  endpoints:
    web:
      exposure:
        #include: health,info,prometheus
        include: health,info,prometheus # 暴露/actuator/prometheus
  metrics:
    tags:
      application: ${spring.application.name} # 暴露的数据中添加application label